# -*- coding: utf-8 -*-
"""HBM_vs_DDR5_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYHD1e2pZayc5lYsse4gvAzvRxvi0Yzf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# The actual "dataset" we are creating manually for comparison
data = {
    'Memory_Type': ['HBM3E (AI Accelerator)', 'DDR5 (Standard Server)'],
    # Bandwidth in GB/s. We use a high HBM figure to show the clear difference
    'Max_Bandwidth_GBs': [1200, 50],
    'Architecture': ['3D Stacked', '2D Planar'],
    'Bus_Width': [1024, 64]
}

# Create a Pandas DataFrame (a structured table)
df = pd.DataFrame(data)

print("--- Data Review ---")
print(df)

# Set the style for a professional look
sns.set_style("whitegrid")

# Create the figure and axes for the plot
plt.figure(figsize=(10, 6)) # Sets the size of the chart

# Create the bar chart
# x= will be the Memory Type, y= will be the Bandwidth value
barplot = sns.barplot(
    x='Memory_Type',
    y='Max_Bandwidth_GBs',
    data=df,
    palette=['#FF5733', '#337AFF'] # Custom colors for better visual separation
)

# Add the exact value labels on top of the bars
for bar in barplot.patches:
    barplot.annotate(
        format(bar.get_height(), '.0f') + ' GB/s', # Format as a whole number
        (bar.get_x() + bar.get_width() / 2., bar.get_height()),
        ha = 'center',
        va = 'center',
        xytext = (0, 9),
        textcoords = 'offset points',
        fontsize=12,
        fontweight='bold'
    )

# Set the Title and Labels
plt.title(
    'Bandwidth Showdown: HBM3E vs. High-End DDR5',
    fontsize=16,
    fontweight='bold',
    pad=20
)
plt.ylabel('Max Bandwidth (GB/s)', fontsize=14)
plt.xlabel('Memory Type', fontsize=14)
plt.ylim(0, 1400) # Set a consistent y-limit for better visual impact

# Display the plot
plt.show()

# Data representing the approximate relative cost per GB
cost_data = {
    'Memory_Type': ['Standard DDR5', 'High-Bandwidth Memory (HBM3E)'],
    # Relative Cost (Normalized: DDR5 = 1)
    'Relative_Cost_per_GB': [1.0, 5.0],
    'Explanation': ['Lower Manufacturing Complexity', '3D Stacking & Interposer (CoWoS)']
}

df_cost = pd.DataFrame(cost_data)

print("--- Relative Cost Data ---")
print(df_cost)

# Set the style
sns.set_style("whitegrid")

# Create the figure and axes for the plot
plt.figure(figsize=(8, 6))

# Create the bar chart for relative cost
barplot_cost = sns.barplot(
    x='Memory_Type',
    y='Relative_Cost_per_GB',
    data=df_cost,
    palette=['#33A02C', '#E31A1C'] # Green for lower cost, Red for higher
)

# Add the exact value labels on top of the bars
for bar in barplot_cost.patches:
    barplot_cost.annotate(
        f'{bar.get_height():.1f}x', # Format with one decimal
        (bar.get_x() + bar.get_width() / 2., bar.get_height()),
        ha = 'center',
        va = 'center',
        xytext = (0, 9),
        textcoords = 'offset points',
        fontsize=14,
        fontweight='bold'
    )

# Set the Title and Labels
plt.title(
    'The Economic Factor: Relative Cost per Gigabyte (DDR5 = 1x)',
    fontsize=14,
    fontweight='bold',
    pad=20
)
plt.ylabel('Relative Cost Multiplier', fontsize=12)
plt.xlabel('Memory Type', fontsize=12)
plt.ylim(0, 6) # Set a consistent y-limit

# Display the plot
plt.show()

# Data representing the approximate Power Efficiency
efficiency_data = {
    'Memory_Type': ['High-Bandwidth Memory (HBM)', 'GDDR6 (High-End GPU)'],
    # Power Efficiency in GB/s per Watt
    'Efficiency_GBs_per_Watt': [65, 45],
}

df_efficiency = pd.DataFrame(efficiency_data)

print("--- Power Efficiency Data ---")
print(df_efficiency)

# Set the style
sns.set_style("whitegrid")

# Create the figure and axes for the plot
plt.figure(figsize=(8, 6))

# Create the bar chart for power efficiency
barplot_efficiency = sns.barplot(
    x='Memory_Type',
    y='Efficiency_GBs_per_Watt',
    data=df_efficiency,
    palette=['#00CC99', '#FF9933'] # A contrast of Green and Orange
)

# Add the exact value labels on top of the bars
for bar in barplot_efficiency.patches:
    barplot_efficiency.annotate(
        f'{bar.get_height():.0f} GB/s per Watt',
        (bar.get_x() + bar.get_width() / 2., bar.get_height()),
        ha = 'center',
        va = 'center',
        xytext = (0, 9),
        textcoords = 'offset points',
        fontsize=12,
        fontweight='bold'
    )

# Set the Title and Labels
plt.title(
    'Power Efficiency Comparison: HBM vs. GDDR6',
    fontsize=14,
    fontweight='bold',
    pad=20
)
plt.ylabel('Efficiency (GB/s per Watt)', fontsize=12)
plt.xlabel('Memory Type', fontsize=12)
plt.ylim(0, 80)

# Display the plot
plt.show()